name: Google Chat
description: "Send a message to Google Chat"

inputs:
  webhook-url:
    description: "Google Chat Webhook URL"
    required: true
    type: string
  status:
    description: "success or failure or cancelled"
    default: "success"
    type: string
  title:
    description: "タイトル"
    type: string
  subtitle:
    description: "サブタイトル"
    type: string
  message:
    description: "メッセージ"
    type: string
  url:
    description: "URL"
    type: string

runs:
  using: "composite"
  steps:
    - id: url
      run: |
        echo "url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> "$GITHUB_OUTPUT"
      shell: bash
    - run: |
        jq -n \
        --arg status "<font color=\"${COLOR}\"><b>${STATUS}</b></font>" \
        --arg title "${TITLE}" \
        --arg subtitle "${SUBTITLE}" \
        --arg message "${MESSAGE}" \
        --arg job "${JOB}" \
        --arg url "${URL}" \
        '{
          "cardsV2": [
            {
              "card": {
                "header": {
                  "title": $title,
                  "subtitle": $subtitle,
                  "imageUrl": "https://octodex.github.com/images/original.png"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "decoratedText": {
                          "text": $status
                        }
                      },
                      {
                        "textParagraph": {
                          "text": $message
                        }
                      },
                      {
                        "buttonList": {
                          "buttons": [
                            {
                              "text": $job,
                              "onClick": {
                                "openLink": {
                                  "url": $url
                                }
                              }
                            }
                          ]
                        }
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }' | curl -X POST -H "Content-Type: application/json" -d @- "${{ inputs.webhook-url }}"
      shell: bash
      env:
        STATUS: ${{ inputs.status }}
        COLOR: ${{ (inputs.status == 'success' && '#31AF91') || '#FF0B0B' }}
        TITLE: ${{ inputs.title && inputs.title || github.repository }}
        SUBTITLE: ${{ inputs.subtitle && inputs.subtitle || github.job }}
        MESSAGE: ${{ inputs.message }}
        JOB: "Go to ${{ github.job }}"
        URL: "${{ inputs.url && inputs.url || steps.url.outputs.url }}"
