name: GitHub App Token
description: "Create a GitHub App token for the repository"

inputs:
  app_id:
    description: "vars.APP_ID"
    required: true
  private_key:
    description: "secrets.PRIVATE_KEY"
    required: true

runs:
  using: "composite"
  steps:
    - id: app-token
      uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: ${{ github.repository_owner }}
    - run: git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com".insteadOf "https://github.com"
      shell: bash
