name: GitHub App Token
inputs:
  app_id:
    description: "vars.APP_ID"
    required: true
  private_key:
    description: "secrets.PRIVATE_KEY"
    required: true
runs:
  using: "composite"
  steps:
    - id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: ${{ github.repository_owner }}
    - run: git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com".insteadOf "https://github.com"
      shell: bash
