name: Notify

on:
  workflow_dispatch:
    inputs:
      status:
        description: "Status"
        required: true
        default: "success"
        options:
          - success
          - failure
          - cancelled
        type: choice

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: inputs.status == 'success'
        id: changelog
        uses: ./.github/actions/changelog
      - if: inputs.status == 'success'
        uses: ./.github/actions/google-chat
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          title: "${{ github.repository }} ${{ steps.changelog.outputs.tag_name }}"
          message: "${{ steps.changelog.outputs.changelog }}"
          url: "${{ steps.changelog.outputs.html_url }}"
          status: "${{ inputs.status }}"
      - if: inputs.status == 'failure'
        uses: ./.github/actions/google-chat
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          status: "${{ inputs.status }}"
