name: Notify

on:
  workflow_dispatch:
    inputs:
      status:
        description: "Status"
        required: true
        default: "success"
        options:
          - success
          - failure
          - cancelled
        type: choice

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - if: inputs.status == 'success'
        id: changelog
        uses: ./.github/actions/changelog
      - if: inputs.status == 'success'
        uses: ./.github/actions/google-chat
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          title: "${{ github.repository }} ${{ steps.changelog.outputs.tag_name }}"
          message: "${{ steps.changelog.outputs.changelog }}"
          url: "${{ steps.changelog.outputs.html_url }}"
          status: "${{ inputs.status }}"
      - if: inputs.status == 'failure'
        uses: ./.github/actions/google-chat
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          status: "${{ inputs.status }}"
